### ISSUE TITLE
Version not deployed?

### ISSUE THREAD

**Issue by crdoconnor** [awalsh128/cache-apt-pkgs-action-ci#4]
Not sure if this is expected or not but I'm getting this:

```
Error: Unable to resolve action `awalsh128/cache-apt-pkgs-action@1.1.0`, unable to find version `1.1.0`

Error: Unable to resolve action `awalsh128/cache-apt-pkgs-action@latest`, unable to find version `latest`
```

Really looking forward to there being an action for this, by the way. It'll be a great help.

**Comment by awalsh128** [comment]
Hi @crdoconnor, the version should be prefixed by a v (i.e. `awalsh128/cache-apt-pkgs-action@v1.1.0`).

RE: latest, I need to create this and set it up in my release workflow. Will open another issue for this.

**Comment by crdoconnor** [comment]
Thanks. Using v1.1.0 got it running but that triggered another issue - it didn't work for the packages I tried with. I'll create a mini repo to illustrate it.
